### ISSUE TITLE
Code of Conduct Communication & Framing

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/opencon-dei-report#12]
Add additional information in the CoC section of report around framing and communicating seriousness of diversity/anti-harassment policies (rather than "Be friendly")

**Comment by char-siuu-bao** [comment]
We've done this! We have a COC short version that's at the top of the webpage here: http://www.opencon2017.org/code_of_conduct

**Code of Conduct in Brief** 

Our Code of Conduct, in brief, covers three main things:

1. Physical, sexual, and verbal harassment are unacceptable: we have a zero tolerance policy. 
2. Don’t discriminate against people because of their identity (e.g. race, gender, sexuality, age, class background, ability, religion and more).
3. We expect participants to work together to create a welcoming, inclusive, and safe(r) environment for people from diverse backgrounds.

You should take the time to read about what constitutes harassment and discrimination in our full Code of Conduct (below!). However, here are some rules of thumb to keep in mind when checking whether you are putting the Code of Conduct into practice:

**Ask for consent (i.e. permission), and respect people’s boundaries.**
Ask for permission before you engage in physical interactions with participants (this applies to everything from friendly interactions, such as asking “Can I hug you?” before you hug someone—to sexual attention and/or sexualized physical contact at conference social events or after hours, off-site). If they say no, respect that and don’t continue. Sexual harassment is unacceptable, including on online, at conference social events, and after-hours at the conference.

**Be careful about the words you use. Is the language that you’re using discriminatory?**
There is a lot of everyday language which discriminates against people. Using racial slurs, or phrases like “that’s lame”, “that’s gay”, or “that’s retarded” may seem harmless to some, but actually discriminates against minorities such as people of colour, LGBTQ+ people, or those with disabilities. If someone calls you out for using problematic language, please take the time to listen, apologize, and put effort into not using the language again. You may be asked to leave the community for using this kind of language.

**Be mindful of how much time and space you’re taking up. Be aware of your power and privilege, and whether you’re taking advantage of it.**
Are you a man who is taking up all the time for questions in a workshop full of mostly female participants? Are you a Western academic who isn’t giving a chance for a participant from an underrepresented country to speak? Are you attempting to engage in a physical or intimate interaction with someone who doesn’t have the capacity to consent? (E.g. at an evening social event with alcohol). Are you taking the time to listen to the perspectives of those who are different from you?

**Comment by gedankenstuecke** [comment]
Well done! 🎉
